# Generated by Django 3.2.25 on 2024-05-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_overbuxef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenha',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_creacion',
            field=models.DateTimeField(default='2024-05-09'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default='2024-05-09'),
        ),
    ]
