# Generated by Django 3.2.25 on 2024-05-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_overbuxef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='anonimo',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_creacion',
            field=models.DateTimeField(default='2024-05-03'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default='2024-05-03'),
        ),
    ]
