# Generated by Django 3.2.25 on 2024-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_overbuxef', '0002_auto_20240509_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_creacion',
            field=models.DateTimeField(default='2024-05-10'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default='2024-05-10'),
        ),
    ]
